require 'rake/testtask'
require 'find'
require 'bundler/gem_tasks'

desc 'Say Hello'
task :hello do
  puts "Hello this is the hello task"
end

desc 'Run Tests'
task default: :test

Rake::TestTask.new(:test) do |t|
  t.libs << 'lib'
  t.libs << 'test'
  t.test_files = FileList['test/**/*_test.rb']
end

desc 'Display all files'
task :all_files do
  Find.find('.') do |name|
    next if name.include?('\.')
    puts name if File.file?(name)
  end
end
